spring.application.name=tradesim-backend

# Server configurations
server.servlet.context-path=/api

# Database configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.throw-exception-if-no-handler-found=true
# use following options only when you want to import data
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true

# jwt configurations
jwt.secret=${JWT_SECRET}
jwt.expiration=1800000
jwt.refresh-expiration=604800000

# cookie configs
auth.refresh-token.cookie-name=refreshToken
auth.refresh-token.cookie-path=/api/auth
# make this true when using https
auth.refresh-token.cookie-secure=false
auth.refresh-token.cookie-same-site=Lax

forex.api.url=https://api.frankfurter.dev/v2/rates